# Generated by Django 4.2.27 on 2025-12-13 21:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del cultivo')),
                ('turno_estimado', models.PositiveIntegerField(help_text='Años desde la siembra hasta la cosecha', verbose_name='Turno estimado (años)')),
                ('densidad_base', models.PositiveIntegerField(default=1111, help_text='Número de árboles por hectárea en siembra inicial', verbose_name='Densidad base (árboles/ha)')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la zona')),
                ('costo_jornal_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo jornal base (S/)')),
                ('factor_flete', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Factor de flete')),
            ],
            options={
                'verbose_name': 'Zona Económica',
                'verbose_name_plural': 'Zonas Económicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('cod_ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código UBIGEO')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del distrito')),
                ('pendiente_promedio_estimada', models.PositiveSmallIntegerField(default=15, help_text='Pendiente promedio estimada del terreno en porcentaje', verbose_name='Pendiente promedio (%)')),
                ('factor_acceso_temporal', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Factor de ajuste por accesibilidad (1.0 = normal, >1 = difícil)', max_digits=4, verbose_name='Factor de acceso')),
                ('zona_economica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos', to='gestion_forestal.zonaeconomica', verbose_name='Zona económica')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_proyecto', models.PositiveSmallIntegerField(default=0, help_text='0 = año de instalación', verbose_name='Año del proyecto')),
                ('rubro', models.CharField(choices=[('MANO_OBRA', 'Mano de Obra'), ('INSUMO', 'Insumos'), ('SERVICIOS', 'Servicios'), ('LEGAL', 'Legal/Administrativo'), ('ACTIVO', 'Activos Fijos')], max_length=20, verbose_name='Rubro de costo')),
                ('actividad', models.CharField(max_length=200, verbose_name='Actividad')),
                ('unidad_medida', models.CharField(help_text='Ej: Jornal, Kg, Unidad, Global', max_length=50, verbose_name='Unidad de medida')),
                ('cantidad_tecnica', models.DecimalField(decimal_places=2, help_text='Cantidad requerida por hectárea en terreno plano', max_digits=10, verbose_name='Cantidad técnica')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo por unidad (para insumos/servicios). Si es 0, usa costo jornal.', max_digits=10, verbose_name='Costo unitario (S/)')),
                ('sensible_pendiente', models.BooleanField(default=False, help_text='Si la pendiente del terreno afecta el rendimiento de la actividad', verbose_name='Sensible a pendiente')),
                ('es_recalce', models.BooleanField(default=False, help_text='Si es reposición por mortalidad de plantas', verbose_name='Es recalce')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_tecnologico', to='gestion_forestal.cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Paquete Tecnológico',
                'verbose_name_plural': 'Paquetes Tecnológicos',
                'ordering': ['cultivo', 'anio_proyecto', 'rubro', 'actividad'],
                'unique_together': {('cultivo', 'anio_proyecto', 'actividad')},
            },
        ),
    ]
