# Generated by Django 4.2.27 on 2025-12-13 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='factor_acceso_temporal',
        ),
        migrations.RemoveField(
            model_name='paquetetecnologico',
            name='costo_unitario',
        ),
        migrations.RemoveField(
            model_name='paquetetecnologico',
            name='es_recalce',
        ),
        migrations.RemoveField(
            model_name='zonaeconomica',
            name='costo_jornal_base',
        ),
        migrations.RemoveField(
            model_name='zonaeconomica',
            name='factor_flete',
        ),
        migrations.AddField(
            model_name='distrito',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada para marcador visual en mapa', max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada para marcador visual en mapa', max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='paquetetecnologico',
            name='costo_unitario_referencial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Para insumos/servicios que NO son plantones ni mano de obra', max_digits=10, verbose_name='Costo unitario referencial (S/)'),
        ),
        migrations.AddField(
            model_name='paquetetecnologico',
            name='es_planton',
            field=models.BooleanField(default=False, help_text='True si este insumo corresponde a plantones forestales', verbose_name='Es plantón'),
        ),
        migrations.AddField(
            model_name='zonaeconomica',
            name='costo_jornal_referencial',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Valor sugerido para el frontend', max_digits=8, verbose_name='Costo jornal referencial (S/)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zonaeconomica',
            name='costo_planton_referencial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Valor sugerido para el frontend', max_digits=8, verbose_name='Costo plantón referencial (S/)'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='pendiente_promedio_estimada',
            field=models.PositiveSmallIntegerField(default=15, help_text='Pendiente promedio estimada del terreno', verbose_name='Pendiente promedio (%)'),
        ),
        migrations.AlterField(
            model_name='paquetetecnologico',
            name='sensible_pendiente',
            field=models.BooleanField(default=False, help_text='Si la pendiente afecta el rendimiento (solo para mano de obra)', verbose_name='Sensible a pendiente'),
        ),
    ]
