# Generated by Django 4.2.27 on 2025-12-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0002_remove_distrito_factor_acceso_temporal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetetecnologico',
            name='sensible_densidad',
            field=models.BooleanField(default=False, help_text='True si el costo escala con la densidad de siembra (ej: plantones, hoyado)', verbose_name='Sensible a densidad'),
        ),
    ]
