# Generated by Django 4.2.27 on 2025-12-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0003_paquetetecnologico_sensible_densidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='departamento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Provincia'),
        ),
    ]
