# Generated by Django 4.2.27 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0004_distrito_departamento_distrito_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True, verbose_name='Región / Departamento')),
                ('nivel_maleza', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20, verbose_name='Nivel de Maleza')),
                ('dias_limpieza', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Días Limpieza (Jornales)')),
                ('dias_poda', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Días Poda (Jornales)')),
                ('costo_insumos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Insumos (S/)')),
                ('jornal_referencial', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Jornal Referencial (S/)')),
            ],
            options={
                'verbose_name': 'Parámetro Mantenimiento',
                'verbose_name_plural': 'Parámetros Mantenimiento',
            },
        ),
    ]
