# Generated by Django 4.2.27 on 2025-12-18 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0005_parametromantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetetecnologico',
            name='zona_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_tecnologicos', to='gestion_forestal.zonaeconomica', verbose_name='Zona Económica (Opcional)'),
        ),
    ]
