# Generated by Django 4.2.27 on 2025-12-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0006_paquetetecnologico_zona_economica'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paquetetecnologico',
            unique_together={('cultivo', 'zona_economica', 'anio_proyecto', 'actividad')},
        ),
    ]
