# Generated by Django 4.2.27 on 2025-12-23 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_forestal', '0007_alter_paquetetecnologico_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='precio_madera_referencial',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Precio referencial de venta por metro cúbico en pie', max_digits=10, verbose_name='Precio Madera (S/ per m3)'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='rendimiento_m3_ha',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text='Volumen total de madera estimado al final del turno', max_digits=10, verbose_name='Rendimiento (m3/ha)'),
        ),
    ]
